baseURL = "https://keepcodingkeepclimbing.com"
defaultContentLanguage = "en"
theme = "hugo-devresume-theme"
title = "Keep Coding, Keep Climbing"
enableRobotsTXT = true
enableEmoji = true
googleAnalytics = "UA-165309045-1"

[params]
author = "Masahiro Hiramori"
description = "programming and rock climbing"
primaryColor = "#54B689"
textPrimaryColor = "#292929"

[params.profile]
enable = true
name = "Masahiro Hiramori"
tagline = "Research Engineer"
avatar = "avatar.jpg"

[params.contact]
enable = true
location = "Kanagawa, Japan"

[[params.contact.list]]
icon = "fas fa-envelope-square"
url = "mailto:#"
text = "mhg00g13@gmail.com"

[params.skills]
enable = true

[[params.skills.list]]
title = "Technical"

[[params.skills.list.items]]
details = "C/C++/Python/Assemby/Go"

[[params.skills.list.items]]
details = "TensorFlow Lite/ONNX Runtime"

[[params.skills.list.items]]
details = "Git/GitHub"

[[params.skills.list.items]]
details = "FPGA/Quartus II/Verilog-HDL"

[[params.skills.list.items]]
details = "Python - C/C++ interoperation"

[[params.skills.list.items]]
details = "Travis CI/GitHub Actions"

[[params.skills.list.items]]
details = "Technology selection"

[[params.skills.list]]
title = "Professional"

[[params.skills.list.items]]
details = "Effective communication"

[[params.skills.list.items]]
details = "Team player"

[[params.skills.list.items]]
details = "Strong problem solver"

[[params.skills.list.items]]
details = "Good time management"

[params.education]
enable = true

[[params.education.list]]
degree = "M. S. in Information Science and Technology"
university = "Osaka Institute of Technology"
dates = "Apr. 2015 - Mar. 2017"

[[params.education.list]]
degree = "B. A. in Information Science and Technology"
university = "Osaka Institute of Technology"
dates = "Apr.2011 - Mar. 2015"

[params.awards]
enable = false

[params.languages]
enable = true

[[params.languages.list]]
name = "Japanese"
level = "Native"

[[params.languages.list]]
name = "English"
level = "Limited working proficiency"

[params.interests]
enable = true

[[params.interests.list]]
name = "Rock climbing"

[[params.interests.list]]
name = "Travelling"

[params.summary]
enable = true
text = "Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."

[params.experience]
enable = true

[[params.experience.list]]
title = "Research Engineer"
dates = "Apr. 2017 - Present"
company = "Mitsubishi Electric Corporation"
details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."

[[params.experience.list.items]]
details = "Lorem ipsum dolor sit amet, consectetuer."

[[params.experience.list.items]]
details = "Aenean commodo ligula eget dolor."

[[params.experience.list.items]]
details = "Etiam ultricies nisi vel augue."

[params.projects]
enable = true

[[params.projects.list]]
title = "Verilog-HDL/SystemVerilog for VSCode extension"
meta = "Open Source"
tagline = ""

[params.information]
enable = true

[[params.information.list]]
title = "Publications"

[[params.information.list.items]]
details = "**Masahiro Hiramori**, Ryota Bandou, Shuhei Iwade, Hiroshi Makino, Tsutomu Yoshimura, Yoshio Matsuda. A study on fast motion estimation algorithm, In IEEE 5th Global Conference on Consumer Electronics, 2016."

[[params.information.list.items]]
details = "Ryota Bnadou, **Masahiro Hiramori**, Shuhei Iwade, Hiroshi Makino, Tutomu Yoshimura, Yoshio Matsuda. A study on motion estimation algorithm for moving pictures, In IEEE 5th Global Conference on Consumer Electronics, 2016."

[[params.information.list]]
title = "Interests"
details = "Rock climbing, Travelling"

[params.social]
enable = true

[[params.social.list]]
icon = "fab fa-github-square"
url = "//github.com/mshr-h"
title = "mshr-h"

[[params.social.list]]
icon = "fab fa-linkedin"
url = "//linkedin.com/in/masahiro-hiramori-63b992167"
title = "masahiro-hiramori-63b992167"

[[params.social.list]]
icon = "fab fa-twitter-square"
url = "//twitter.com/mshrh3"
title = "@mshrh3"

